### ISSUE TITLE
Blurbs Landing Page

### ISSUE THREAD

**Issue by LionOnTheWeb** [LionOnTheWeb/lionontheweb-web#15]
# Overview
Create blurbs landing/archive page. Completion will allow visitors to see a list of blog posts with images (optional), a search bar, filter options and pagination for blurbs.

_**Note:** please develop any methods  in TDD format_

# Tasks
- [ ] Create index component for blurbs directory (blurbs landing page component)
- [ ] Integrate the following components:
    - [ ] Search bar component - with search binded to context of blurb posts
    - [ ] Filter options component - with filter options exposed to search bar component
    - [ ] Pagination component - with pagination binded to context of blurb posts
