### ISSUE TITLE
Automate changelog process

### ISSUE THREAD

**Issue by LionOnTheWeb** [LionOnTheWeb/lionontheweb-web#29]
## Overview
Release branches must be accompanied by a changelog entry and and updated version on the package.json upon merging into the main branch. Create a process that will compare the "version" field in the package.json with the release version in the release branch name and append a changelog entry in a `CHANGELOG.md` file located in the root directory.

## Task
- [ ] Using Husky, create a pre-commit script that runs only when creating a commit on a `release/...` branch
- [ ] In said pre-commit script obtain project version number from package.json and the version number from the release branch name
    - [ ]  If the branch name has a higher version number than the project's package.json, set the branch name version number as our target version number
    - [ ] Determine the type of version update it is (e.g. major.minor.patch) based on the decimal place (refer to [versioning](https://github.com/LionOnTheWeb/lionontheweb-web/blob/main/docs/project-standards.md#versioning) in the project standards doc
- [ ] Use the details of the target version number to append the appropriate changes to the `CHANGELOG.md` (Use changelog document format below as a reference)

### Changelog Document Format
The format for the changelog should align with the type of version update. See below for example reference:

```
# ✨ Major Release vX.0.0 ✨
* Squashed commits in major release

## Minor Release v0.X.0
* <details>
    <summary>Feature 28 - Feature addition summary</summary>
        * Squashed commit messages
    </details>

* <details>
    <summary>Config 56 - Config addition summary</summary>
        * Squashed commit messages
    </details>

### Patch Notes
* <details>
    <summary>Update v0.0.X - d/at/e</summary>
        * Bugfix 31 - bugfix summary
        * Hotfix 43 - hotfix summary
        * ...other summaries/squashed commit messages
    </details>
```
