### ISSUE TITLE
Determine design aesthetic

### ISSUE THREAD

**Issue by LionOnTheWeb** [LionOnTheWeb/lionontheweb-web#31]

**Comment by LionOnTheWeb** [comment]
# Overview
The decided overarching aesthetic for LionOnTheWeb.com is NYC; because this is where I've spent much of my time growing into the person I am today, as such is the perfect muse for my personal portfolio website. 

I need to research what parts of NYC I want to represent on my website. What easter egg of my experiences can I reference to give a taste to the site's visitors?

# Task
- [ ] Research and pick what aspects of NYC I want to convey on LionOnTheWeb.com
    - [ ] How can these aspects be conveyed? Color, animation/movement, interactivity, structure/dimensions?
    - [ ] Briefly list them link other issues that relate in the comment section

# References
* Doc - [ Link Issues in Github Markdown ] ( [ref url](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls) )
