### ISSUE TITLE
Configure Vitest in SvelteKit

### ISSUE THREAD

**Issue by LionOnTheWeb** [LionOnTheWeb/lionontheweb-web#5]
# Overview
Add Vitest configuration to SvelteKit project

# Tasks
- [ ] Install vitest as a dev dependency
- [ ] Add a config file for vitest (Or use existing `vite.config.js`)
- [ ] Add a vitest `"test"` script in `package.json`

# References
* Doc - [How to write tests in sveltekit and vitest](https://www.eternaldev.com/blog/how-to-write-tests-in-sveltekit-and-vitest/)

**Comment by LionOnTheWeb** [comment]
_**Note:** Additional configuration may be appropriate when writing our first tests in #6 or #7_ 

## Additional References
* Youtube - [Svelte-Kit Dev Is No Longer Available Use Vite Dev Instead](https://www.youtube.com/watch?v=DSaRNhPpwMM)
* Youtube - [🧪 Test SvelteKit with TDD & VITEST 🧪](https://www.youtube.com/watch?v=5bQD3dCoyHA)
